# Generated by Django 5.2.14 on 2026-05-19 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organization_wa_phone_number_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('message_template', models.TextField(max_length=4096)),
                ('audience_filter', models.CharField(choices=[('all', 'All Leads'), ('new', 'New Leads'), ('warm', 'Warm Leads'), ('qualified', 'Qualified Leads'), ('cold', 'Cold Leads'), ('buy', 'Buy Intent'), ('sell', 'Sell Intent'), ('rent', 'Rent Intent'), ('invest', 'Investment Intent')], default='all', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='If set, campaign sends at this time. If null, send immediately on trigger.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.organization')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='campaigns_organiz_0c0cd6_idx'), models.Index(fields=['status', 'scheduled_at'], name='campaigns_status_fe06f1_idx')],
            },
        ),
    ]
