# Generated by Django 5.2.14 on 2026-05-26 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('leads', '0015_follow_up_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='area_interest',
            field=models.CharField(blank=True, help_text='Substring match on lead.city_interest', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_max',
            field=models.BigIntegerField(blank=True, help_text='Include leads whose budget_min <= this value', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_min',
            field=models.BigIntegerField(blank=True, help_text='Include leads whose budget_max >= this value', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='messaging_tier',
            field=models.PositiveSmallIntegerField(default=1, help_text='Meta Business messaging tier: 1=1k/day, 2=10k/day, 3=100k/day'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_template_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_template_language',
            field=models.CharField(default='en_US', max_length=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_template_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_template',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='leads.lead')),
            ],
            options={
                'db_table': 'campaign_recipients',
                'indexes': [models.Index(fields=['campaign', 'delivery_status'], name='campaign_re_campaig_f3f16e_idx')],
                'unique_together': {('campaign', 'lead')},
            },
        ),
    ]
