# Generated by Django 5.2.14 on 2026-05-29 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_fields_recipient'),
        ('leads', '0017_referral_link'),
        ('organizations', '0019_rename_dev_api_keys_org_active_idx_developer_a_organiz_70be96_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='UUID4-based unguessable slug', max_length=40, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, help_text='The lead who shared the link (null = org-level link)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_links', to='leads.lead')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to='organizations.organization')),
            ],
            options={
                'db_table': 'campaign_referral_links',
                'unique_together': {('org', 'lead')},
            },
        ),
    ]
