# Generated by Django 5.2.14 on 2026-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisecurityevent',
            name='event_type',
            field=models.CharField(choices=[('sql_injection', 'SQL Injection'), ('cross_tenant', 'Cross-Tenant Access'), ('jwt_anomaly', 'JWT Anomaly'), ('auth_failure', 'Auth Failure'), ('rate_limit_blocked', 'Rate-Limit Block'), ('suspicious_header', 'Suspicious Header'), ('parameter_tampering', 'Parameter Tampering')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='apisecurityevent',
            name='severity',
            field=models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=3),
        ),
    ]
