# Generated by Django 5.2.14 on 2026-05-20 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_organization_wa_phone_number_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('plan', models.CharField(default='trial', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete')], default='trialing', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'db_table': 'billing_subscriptions',
            },
        ),
    ]
