# Generated by Django 5.2.14 on 2026-05-21 12:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_orgsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=30)),
                ('event_id', models.CharField(max_length=500)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'billing_webhook_events',
                'indexes': [models.Index(fields=['gateway', 'event_id'], name='billing_web_gateway_909270_idx')],
                'unique_together': {('gateway', 'event_id')},
            },
        ),
    ]
