# Generated by Django 5.2.14 on 2026-05-30 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0018_lead_is_sandbox'),
        ('organizations', '0022_organization_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgVoiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(blank=True, max_length=100)),
                ('auth_token', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='E.164 Twilio phone number, e.g. +15551234567', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('record_calls', models.BooleanField(default=False)),
                ('ai_voice_name', models.CharField(default='Polly.Joanna', help_text='Twilio TTS voice, e.g. Polly.Joanna, Polly.Amy', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_config', to='organizations.organization')),
            ],
            options={
                'db_table': 'org_voice_configs',
            },
        ),
        migrations.CreateModel(
            name='VoiceCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_sid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('from_phone', models.CharField(max_length=20)),
                ('to_phone', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('ai_handling', 'AI Handling'), ('agent_joined', 'Agent Joined'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='ringing', max_length=20)),
                ('barge_in_at', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True)),
                ('ai_context_snapshot', models.JSONField(blank=True, default=dict)),
                ('recording_url', models.URLField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barge_in_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barge_in_calls', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='leads.lead')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_calls', to='organizations.organization')),
            ],
            options={
                'db_table': 'voice_call_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='voice_call__organiz_e69240_idx'), models.Index(fields=['from_phone'], name='voice_call__from_ph_226756_idx')],
            },
        ),
    ]
