# Generated by Django 5.0.6 on 2026-05-05 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("city", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=300)),
                (
                    "area_marla",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_pkr", models.BigIntegerField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("plot", "Plot"),
                            ("industrial", "Industrial"),
                        ],
                        default="residential",
                        max_length=30,
                    ),
                ),
                (
                    "legal_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Unverified"),
                            ("verified", "Verified"),
                            ("disputed", "Disputed"),
                            ("pending", "Pending Verification"),
                        ],
                        default="unverified",
                        max_length=30,
                    ),
                ),
                ("ai_score", models.SmallIntegerField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("raw_docs", models.JSONField(blank=True, default=dict)),
                ("ai_analysis", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "properties",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["city"], name="properties_city_c34f4f_idx"),
                    models.Index(
                        fields=["ai_score"], name="properties_ai_scor_cd7c09_idx"
                    ),
                    models.Index(
                        fields=["legal_status"], name="properties_legal_s_ef3220_idx"
                    ),
                    models.Index(
                        fields=["owner"], name="properties_owner_i_921947_idx"
                    ),
                ],
            },
        ),
    ]
