# Generated by Django 5.0.6 on 2026-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="construction_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("builder", "Builder / New"),
                    ("ready", "Ready"),
                    ("under_construction", "Under Construction"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="furnished_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("furnished", "Furnished"),
                    ("unfurnished", "Unfurnished"),
                    ("semi_furnished", "Semi-Furnished"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
