# Generated by Django 5.2.14 on 2026-05-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_role_model_relationships'),
        ('properties', '0002_add_furnished_construction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agent responsible for selling this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to='agents.agent'),
        ),
    ]
