# Generated by Django 5.2.14 on 2026-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_role_model_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='installment_available',
            field=models.BooleanField(default=False),
        ),
    ]
