# Generated by Django 5.2.14 on 2026-05-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ref_no',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated reference number, e.g. PP-LHR-2026-000000001', max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='PropertyRefCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'property_ref_counters',
                'unique_together': {('city_code', 'year')},
            },
        ),
    ]
