# Generated by Django 5.2.14 on 2026-05-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_add_country_currency'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='prop_org_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='ref_no',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated reference number, e.g. RT-LHR-2026-000000001', max_length=30, unique=True),
        ),
    ]
