# Generated by Django 5.2.14 on 2026-05-20 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_add_user_index'),
        ('organizations', '0005_organization_wa_phone_number_id'),
        ('properties', '0012_rename_price_pkr_to_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_listing_f44c8e_idx',
            old_name='prop_owner_type_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_organiz_814279_idx',
            old_name='prop_org_active_idx',
        ),
        migrations.AlterField(
            model_name='property',
            name='area_marla',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric size in the unit specified by area_unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Agent responsible for selling/renting this property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_properties', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='currency',
            field=models.CharField(default='PKR', help_text='ISO 4217 currency code, e.g. PKR, AED, USD, GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Set when listing_owner_type=organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Set when listing_owner_type=client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.BigIntegerField(blank=True, help_text='Price in the currency specified by the currency field', null=True),
        ),
    ]
