# Generated by Django 5.2.14 on 2026-05-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_propert_f38ecc_idx',
            old_name='properties_prop_type_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_price_aa33af_idx',
            old_name='properties_price_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_is_acti_5a3c66_idx',
            old_name='properties_active_city_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_is_acti_1368fa_idx',
            old_name='properties_active_created_idx',
        ),
    ]
