# Generated by Django 5.2.14 on 2026-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_rename_properties_prop_type_idx_properties_propert_f38ecc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Canonical area in square metres — auto-computed from area_marla + area_unit on save', max_digits=12, null=True),
        ),
    ]
