# Generated by Django 5.2.14 on 2026-05-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_populate_area_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS-84 latitude — enables haversine geo-search', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS-84 longitude — enables haversine geo-search', max_digits=9, null=True),
        ),
    ]
