# Generated by Django 5.2.14 on 2026-05-08 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_role_model_relationships'),
        ('escrow', '0001_initial'),
        ('properties', '0003_role_model_relationships'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowdeal',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent who facilitated this deal lock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_locks', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='initiated_via',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard')], default='whatsapp', max_length=20),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='lock_started_at',
            field=models.DateTimeField(blank=True, help_text='When admin confirmed payment', null=True),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('bank', 'Bank Transfer'), ('safepay', 'Safepay'), ('manual', 'Manual (Admin)')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='escrowdeal',
            name='payment_ref',
            field=models.CharField(blank=True, help_text='Gateway transaction ID or bank ref', max_length=200),
        ),
        migrations.AlterField(
            model_name='escrowdeal',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, help_text='lock_started_at + 48h', null=True),
        ),
        migrations.AlterField(
            model_name='escrowdeal',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escrow_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='escrowdeal',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('locked', 'Locked'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('expired', 'Expired')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrowdeal',
            name='token_amount',
            field=models.BigIntegerField(help_text='Token amount in PKR (25,000–100,000)'),
        ),
        migrations.AddIndex(
            model_name='escrowdeal',
            index=models.Index(fields=['status'], name='escrow_deal_status_68b1c7_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowdeal',
            index=models.Index(fields=['property'], name='escrow_deal_propert_0fb190_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowdeal',
            index=models.Index(fields=['buyer'], name='escrow_deal_buyer_i_6fd55f_idx'),
        ),
    ]
