# Generated by Django 5.2.14 on 2026-05-08 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_role_model_relationships'),
        ('escrow', '0002_deal_lock_fields'),
        ('properties', '0004_property_installment_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='escrowdeal',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['initiated', 'locked'])), fields=('property',), name='unique_active_deal_lock_per_property'),
        ),
    ]
