# Generated by Django 5.2.14 on 2026-05-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_escrowdeal_unique_active_deal_lock_per_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowdeal',
            name='seller_confirmation_token',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
