# Generated by Django 5.2.14 on 2026-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_arch_global_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowdeal',
            name='token_amount',
            field=models.BigIntegerField(help_text='Token amount in the currency specified by currency field'),
        ),
    ]
