# Generated by Django 5.2.14 on 2026-05-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0006_alter_escrowdeal_token_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowdeal',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('jazzcash', 'JazzCash (PK)'), ('easypaisa', 'EasyPaisa (PK)'), ('safepay', 'Safepay (PK)'), ('bsecure', 'bSecure (PK)'), ('stripe', 'Stripe'), ('card', 'Card (Online)'), ('bank', 'Bank Transfer'), ('manual', 'Manual (Admin)')], default='manual', max_length=20),
        ),
    ]
