# Generated by Django 5.0.6 on 2026-05-07 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('document_type', models.CharField(choices=[('fard', 'Fard (Ownership Record)'), ('allotment', 'Allotment Letter'), ('sale_deed', 'Sale Deed / Registry'), ('noc', 'No Objection Certificate'), ('tax_cert', 'Tax Certificate'), ('cnic', 'CNIC'), ('poa', 'Power of Attorney'), ('other', 'Other Document')], default='other', max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('cnic_number', models.CharField(blank=True, max_length=20)),
                ('property_address', models.TextField(blank=True)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.CharField(blank=True, max_length=50)),
                ('authority', models.CharField(blank=True, max_length=200)),
                ('extracted_fields', models.JSONField(default=dict)),
                ('red_flags', models.JSONField(default=list)),
                ('confidence', models.CharField(default='LOW', max_length=10)),
                ('raw_ocr', models.TextField(blank=True)),
                ('whatsapp_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('unreadable', 'Unreadable')], default='unreadable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
