# Generated by Django 5.2.14 on 2026-05-08 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_add_reviewer_signal_score_and_scan_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Keyword, phone, CNIC, society name, or any fraud signal', max_length=200, unique=True)),
                ('reason', models.TextField(blank=True, help_text='Why this token was blacklisted')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expiry date. Null = never expires.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_blacklist',
                'ordering': ['-created_at'],
            },
        ),
    ]
