# Generated by Django 5.2.14 on 2026-05-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0004_fraud_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentscan',
            name='document_type',
            field=models.CharField(choices=[('fard', 'Fard (Ownership Record)'), ('allotment', 'Allotment Letter'), ('sale_deed', 'Sale Deed / Registry'), ('noc', 'No Objection Certificate'), ('tax_cert', 'Tax Certificate'), ('cnic', 'CNIC'), ('poa', 'Power of Attorney'), ('title_deed', 'Title Deed (DLD)'), ('oqood', 'Oqood (Off-plan Registration)'), ('emirates_id', 'Emirates ID'), ('title_register', 'Title Register (HM Land Registry)'), ('land_certificate', 'Land Certificate'), ('mortgage_deed', 'Mortgage Deed'), ('passport', 'Passport'), ('driving_licence', 'Driving Licence'), ('other', 'Other Document')], default='other', max_length=20),
        ),
    ]
