# Generated by Django 5.2.14 on 2026-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_add_us_doc_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='certificate_url',
            field=models.URLField(blank=True),
        ),
    ]
