# Generated by Django 5.2.14 on 2026-05-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_whatsappsession_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='conversation_mode',
            field=models.CharField(choices=[('AI_MANAGED', 'AI Managed'), ('AGENT_MANAGED', 'Agent Managed')], db_index=True, default='AI_MANAGED', max_length=20),
        ),
    ]
