# Generated by Django 5.2.14 on 2026-05-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_whatsappsession_conversation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgwhatsappconfig',
            name='waba_id',
            field=models.CharField(blank=True, help_text='Meta WhatsApp Business Account ID (used for template listing)', max_length=50),
        ),
    ]
