# Generated by Django 5.2.14 on 2026-05-26 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_rename_dev_api_keys_org_active_idx_developer_a_organiz_70be96_idx_and_more'),
        ('whatsapp', '0006_orgwhatsappconfig_waba_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgwhatsappconfig',
            name='category_tags',
            field=models.JSONField(blank=True, default=list, help_text='Meta WABA vertical tags e.g. ["REAL_ESTATE"]'),
        ),
        migrations.AddField(
            model_name='orgwhatsappconfig',
            name='directory_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Keyword strings used in Meta Business Directory discovery'),
        ),
        migrations.AddField(
            model_name='orgwhatsappconfig',
            name='localized_greeting',
            field=models.TextField(blank=True, help_text='Greeting shown to directory-sourced users (max 256 chars)'),
        ),
        migrations.AddField(
            model_name='orgwhatsappconfig',
            name='meta_profile_synced_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful Meta Graph API profile push', null=True),
        ),
        migrations.AddField(
            model_name='orgwhatsappconfig',
            name='support_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{"mon":{"open":"09:00","close":"18:00","closed":false},...}'),
        ),
        migrations.CreateModel(
            name='NeighbourhoodZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('centroid_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('centroid_lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('city', models.CharField(help_text='City string for Tier-1 alignment', max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighbourhood_zones', to='organizations.organization')),
            ],
            options={
                'db_table': 'whatsapp_neighbourhood_zones',
            },
        ),
    ]
