# Generated by Django 5.2.14 on 2026-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_discovery_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='conversation_mode',
            field=models.CharField(choices=[('AI_MANAGED', 'AI Managed'), ('AGENT_MANAGED', 'Agent Managed'), ('BLOCKED', 'Blocked (AML)')], db_index=True, default='AI_MANAGED', max_length=20),
        ),
    ]
