# Generated by Django 5.2.14 on 2026-05-29 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_whatsappsession_is_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='copilot_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CopilotRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(choices=[('inventory_card', 'Inventory Card'), ('doc_link', 'Document Link'), ('tax_sheet', 'Tax Sheet'), ('ai_response', 'AI Response')], max_length=20)),
                ('content', models.JSONField()),
                ('source_message_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_recommendations', to='whatsapp.whatsappsession')),
            ],
            options={
                'db_table': 'copilot_recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
