from django.urls import path
from .views import (
    AgentMeView,
    AgentListView,
    AgentAdminDetailView,
    AgentAvailabilityView,
    AgentAvailableListView,
    AgentLeaderboardView,
    AgentRegisterView,
    AgentApproveView,
    AgentRejectView,
    AgentStatsView,
    TeamView,
    TeamMemberView,
    FreelanceProfileView,
    AgentCompaniesHouseVerifyView,
)

urlpatterns = [
    path('',                          AgentListView.as_view(),          name='agents-list'),
    path('me/',                       AgentMeView.as_view(),             name='agents-me'),
    path('me/availability/',          AgentAvailabilityView.as_view(),   name='agents-me-availability'),
    path('freelance-profile/',        FreelanceProfileView.as_view(),    name='agents-freelance-profile'),
    path('available/',                AgentAvailableListView.as_view(),  name='agents-available'),
    path('leaderboard/',              AgentLeaderboardView.as_view(),    name='agents-leaderboard'),
    path('register/',                 AgentRegisterView.as_view(),       name='agents-register'),
    path('verify-companies-house/',   AgentCompaniesHouseVerifyView.as_view(), name='agents-verify-ch'),
    path('team/',                     TeamView.as_view(),                name='agents-team'),
    path('team/<int:agent_id>/',      TeamMemberView.as_view(),          name='agents-team-member'),
    path('<int:pk>/',                 AgentAdminDetailView.as_view(),    name='agents-admin-detail'),
    path('<int:pk>/approve/',         AgentApproveView.as_view(),        name='agents-approve'),
    path('<int:pk>/reject/',          AgentRejectView.as_view(),         name='agents-reject'),
    path('<int:pk>/availability/',    AgentAvailabilityView.as_view(),   name='agents-availability'),
    path('<int:pk>/stats/',           AgentStatsView.as_view(),          name='agents-stats'),
]
