# Generated by Django 5.0.6 on 2026-05-05 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("buy", "Buying"),
                            ("sell", "Selling"),
                            ("rent", "Renting"),
                            ("invest", "Investing"),
                            ("loan", "Loan Inquiry"),
                            ("tax", "Tax Advisory"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("score", models.SmallIntegerField(default=0)),
                ("intent_signals", models.JSONField(blank=True, default=dict)),
                ("city_interest", models.CharField(blank=True, max_length=100)),
                ("budget_min", models.BigIntegerField(blank=True, null=True)),
                ("budget_max", models.BigIntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("last_scored_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "leads",
                "ordering": ["-score", "-created_at"],
            },
        ),
    ]
