# Generated by Django 5.2.14 on 2026-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('warm', 'Warm'), ('qualified', 'Qualified'), ('cold', 'Cold')], default='new', max_length=20),
        ),
    ]
