# Generated by Django 5.2.14 on 2026-05-09 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_last_contacted_at_lead_source_leadactivity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (from client)'), ('outbound', 'Outbound (to client)')], max_length=10)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Dashboard Note')], default='whatsapp', max_length=20)),
                ('body', models.TextField()),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.lead')),
                ('sender', models.ForeignKey(blank=True, help_text='Set for outbound dashboard messages; null for inbound/AI replies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_crm_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
