# Generated by Django 5.2.14 on 2026-05-14 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_conversationmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.SmallIntegerField()),
                ('new_score', models.SmallIntegerField()),
                ('reason', models.CharField(blank=True, help_text='e.g. "AI rescored", "manual override"', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_score_changes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_score_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
