# Generated by Django 5.2.14 on 2026-05-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_data_populate_organization'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='lead_org_idx',
        ),
    ]
