# Generated by Django 5.2.14 on 2026-05-18 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_add_user_index'),
        ('leads', '0010_arch_global_first'),
        ('organizations', '0005_organization_wa_phone_number_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_routing_2ab3c8_idx',
            old_name='lead_routing_state_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_organiz_4a839c_idx',
            old_name='lead_org_routing_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_priorit_375942_idx',
            old_name='lead_priority_idx',
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this lead is scoped to (null = platform-wide / AI queue)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user'], name='leads_user_id_627b00_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', '-created_at'], name='leads_user_id_72f4c9_idx'),
        ),
    ]
