# Generated by Django 5.2.14 on 2026-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_add_user_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('warm', 'Warm'), ('qualified', 'Qualified'), ('cold', 'Cold'), ('blocked_malicious', 'Blocked — Malicious')], default='new', max_length=20),
        ),
    ]
