# Generated by Django 5.2.14 on 2026-05-22 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_status'),
        ('organizations', '0016_data_migrate_membership_admin_to_org_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='E.164 format', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('manual', 'Manual Entry'), ('import', 'Bulk Import')], default='whatsapp', max_length=20)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_contacts', to='organizations.organization')),
            ],
            options={
                'db_table': 'crm_contacts',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_phone_number', models.CharField(max_length=20)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_lang', models.CharField(default='en', max_length=10)),
                ('conversation_count', models.IntegerField(default=0)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='leads.crmcontact')),
            ],
            options={
                'db_table': 'client_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='crmcontact',
            index=models.Index(fields=['organization', 'phone'], name='crm_contact_organiz_bac933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crmcontact',
            unique_together={('organization', 'phone')},
        ),
    ]
