# Generated by Django 5.2.14 on 2026-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_lead_score_factors'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Lead Created'), ('assigned', 'Agent Assigned'), ('status', 'Status Changed'), ('note', 'Note Added'), ('contacted', 'Client Contacted'), ('scored', 'Score Updated'), ('deal_lock', 'Deal Lock Initiated'), ('handover', 'Handover')], max_length=20),
        ),
    ]
