# Generated by Django 5.2.14 on 2026-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_follow_up_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_known_lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS-84 latitude from last dropped location pin', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_known_lon',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='WGS-84 longitude from last dropped location pin', max_digits=9, null=True),
        ),
    ]
