# Generated by Django 5.2.14 on 2026-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_lead_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='referral_code',
            field=models.CharField(blank=True, default='', help_text='Viral referral link code that originated this lead', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('referral_viral', 'Viral Referral'), ('web', 'Web Portal'), ('manual', 'Manual Entry')], default='whatsapp', max_length=20),
        ),
    ]
