# Generated by Django 5.2.14 on 2026-05-29 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('organizations', '0019_rename_dev_api_keys_org_active_idx_developer_a_organiz_70be96_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datadeletionrequest',
            name='erasure_scope',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datadeletionrequest',
            name='regulation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='datadeletionrequest',
            name='request_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('automated', 'Automated')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='datadeletionrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datadeletionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PIIDetectionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('whatsapp_webhook', 'WhatsApp Webhook'), ('api_submission', 'API Submission'), ('ai_response', 'AI Response'), ('log_write', 'Log Write')], max_length=30)),
                ('field_path', models.CharField(blank=True, max_length=255)),
                ('pattern_name', models.CharField(max_length=30)),
                ('masked_value', models.CharField(max_length=100)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_detection_events', to='organizations.organization')),
            ],
            options={
                'db_table': 'compliance_pii_detection_events',
            },
        ),
        migrations.CreateModel(
            name='PrivacyAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('pii_detected', 'PII Detected'), ('erasure_initiated', 'Erasure Initiated'), ('erasure_completed', 'Erasure Completed'), ('consent_change', 'Consent Change'), ('export_generated', 'Export Generated'), ('data_transfer_checked', 'Data Transfer Checked')], max_length=30)),
                ('subject_identifier', models.CharField(blank=True, max_length=64)),
                ('jurisdiction', models.CharField(blank=True, max_length=20)),
                ('regulation', models.CharField(blank=True, max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_audit_logs', to='organizations.organization')),
            ],
            options={
                'db_table': 'compliance_privacy_audit_logs',
            },
        ),
    ]
