# Generated by Django 5.2.14 on 2026-05-29 09:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_privacy_audit_models'),
        ('escrow', '0006_alter_escrowdeal_token_amount'),
        ('organizations', '0019_rename_dev_api_keys_org_active_idx_developer_a_organiz_70be96_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSanctionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('id_number_prefix', models.CharField(blank=True, max_length=4)),
                ('id_number_hash', models.CharField(blank=True, max_length=64)),
                ('id_type', models.CharField(blank=True, choices=[('cnic', 'CNIC'), ('passport', 'Passport'), ('company_reg', 'Company Registration')], max_length=20)),
                ('list_source', models.CharField(choices=[('OFAC', 'OFAC'), ('UN', 'UN Security Council'), ('EU', 'EU Sanctions'), ('FBR_CBR', 'FBR/CBR Pakistan'), ('LOCAL', 'Local Blacklist')], max_length=20)),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='high', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_sanctions', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(blank=True, help_text='null = platform-level record matching all orgs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanction_records', to='organizations.organization')),
            ],
            options={
                'db_table': 'compliance_sanction_records',
            },
        ),
        migrations.CreateModel(
            name='SanctionScreeningResult',
            fields=[
                ('screening_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screened_name', models.CharField(max_length=200)),
                ('id_number_prefix', models.CharField(blank=True, max_length=4)),
                ('id_number_hash', models.CharField(blank=True, max_length=64)),
                ('list_source', models.CharField(blank=True, max_length=20)),
                ('match_type', models.CharField(blank=True, choices=[('exact', 'Exact Match'), ('fuzzy', 'Fuzzy Match'), ('id_match', 'ID Match')], max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('clear', 'Clear'), ('flagged', 'Flagged'), ('blocked', 'Blocked')], default='clear', max_length=20)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('deal_lock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_results', to='escrow.escrowdeal')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_results', to='organizations.organization')),
            ],
            options={
                'db_table': 'compliance_screening_results',
                'indexes': [models.Index(fields=['org', 'screened_at'], name='compliance__org_id_fe96da_idx')],
            },
        ),
    ]
