# Generated by Django 5.2.14 on 2026-05-08 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_deal_lock_fields'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_token',
            field=models.CharField(blank=True, help_text='Gateway checkout session token', max_length=500),
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Redirect URL for online payment', max_length=1000),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('safepay', 'Safepay'), ('bsecure', 'bSecure'), ('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('manual', 'Manual')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Raw webhook payload for audit'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Gateway transaction ID or bank ref', max_length=200),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_token'], name='payments_checkou_e2b293_idx'),
        ),
    ]
