# Generated by Django 5.2.14 on 2026-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_arch_global_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.BigIntegerField(help_text='Amount in the currency specified by the currency field'),
        ),
    ]
