# Generated by Django 5.2.14 on 2026-05-09 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='CNIC must be in the format XXXXX-XXXXXXX-X', regex='^\\d{5}-\\d{7}-\\d$')]),
        ),
    ]
