# Generated by Django 5.2.14 on 2026-05-14 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be 10–15 digits, optionally prefixed with +.', regex='^\\+?[0-9]{10,15}$')]),
        ),
    ]
