# Generated by Django 5.2.14 on 2026-05-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_phone_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('agent', 'Agent'), ('developer', 'Developer'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
