# Generated by Django 5.2.14 on 2026-05-14 09:37

from django.db import migrations


def backfill_role_client(apps, schema_editor):
    User = apps.get_model('users', 'User')
    updated = User.objects.filter(role='user').update(role='client')
    if updated:
        print(f'  Renamed {updated} user record(s) from role=user to role=client')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_role_user_to_client'),
    ]

    operations = [
        migrations.RunPython(backfill_role_client, migrations.RunPython.noop),
    ]
