# Generated by Django 5.2.14 on 2026-05-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cnic_field_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('ops_admin', 'Operations Admin'), ('ai_admin', 'AI Admin'), ('compliance_admin', 'Compliance Admin'), ('billing_admin', 'Billing Admin'), ('support_admin', 'Support Admin')], help_text='Platform-level sub-role. Only set for role=admin users.', max_length=30, null=True),
        ),
    ]
