# Generated by Django 5.2.14 on 2026-05-30 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auth_enhancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in E.164 format: + followed by 7–15 digits, e.g. +923001234567.', regex='^\\+[0-9]{7,15}$')]),
        ),
    ]
