# Generated by Django 5.2.14 on 2026-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalplatformconnection',
            name='base_url',
            field=models.URLField(blank=True, help_text='Required for custom platform'),
        ),
    ]
