# Generated by Django 5.0.6 on 2026-05-07 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agent_type', models.CharField(choices=[('individual', 'Individual Agent'), ('developer', 'Real Estate Developer'), ('agency', 'Agency / Organization')], default='individual', max_length=20)),
                ('phone', models.CharField(help_text='Primary contact number (with country code, e.g. +923001234567)', max_length=20, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number if different from phone', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cnic_number', models.CharField(blank=True, help_text='For individual agents only (format: 12345-1234567-1)', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='agents/photos/')),
                ('company_name', models.CharField(blank=True, help_text='For agencies and developers: official company/brand name', max_length=200)),
                ('designation', models.CharField(blank=True, help_text='e.g. Senior Property Consultant, Director, Branch Manager', max_length=100)),
                ('license_number', models.CharField(blank=True, help_text='REAP / PBTE / local authority registration number', max_length=100)),
                ('years_experience', models.PositiveSmallIntegerField(default=0, help_text='Years of active experience in real estate')),
                ('languages', models.JSONField(default=list, help_text='Languages spoken, e.g. ["Urdu", "English", "Punjabi"]')),
                ('bio', models.TextField(blank=True, help_text='Short professional bio shown to users (2-4 sentences)')),
                ('specializations', models.JSONField(default=list, help_text='List of specialization keys: residential_buy, residential_rent, commercial, plots, new_projects, luxury, industrial')),
                ('cities', models.JSONField(default=list, help_text='Cities covered, e.g. ["Lahore", "Islamabad"]')),
                ('areas', models.JSONField(default=list, help_text='Specific areas/societies, e.g. ["DHA Phase 5", "Gulberg III", "F-7"]')),
                ('primary_city', models.CharField(blank=True, help_text='Main city of operation (used for priority matching)', max_length=100)),
                ('registration_number', models.CharField(blank=True, help_text='SECP company registration or chamber of commerce number', max_length=100)),
                ('ntn_number', models.CharField(blank=True, help_text='FBR National Tax Number', max_length=50)),
                ('website', models.URLField(blank=True)),
                ('office_address', models.TextField(blank=True, help_text='Full office/branch address')),
                ('instagram_handle', models.CharField(blank=True, help_text='Instagram username (without @)', max_length=100)),
                ('facebook_page', models.URLField(blank=True, help_text='Facebook page URL')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin has verified identity and credentials')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable this agent from receiving leads')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured agents appear first in all matches')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Admin-only notes — not shown to users')),
                ('total_leads', models.PositiveIntegerField(default=0, help_text='Total leads routed to this agent')),
                ('total_listings', models.PositiveIntegerField(default=0, help_text='Number of active/historical listings')),
                ('closed_deals', models.PositiveIntegerField(default=0, help_text='Successfully closed transactions')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average user rating out of 5.0', max_digits=3)),
                ('last_active_at', models.DateTimeField(blank=True, help_text='Last time a lead was sent to this agent', null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin user who verified this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'ordering': ['-is_featured', '-is_verified', '-rating', 'name'],
            },
        ),
    ]
