# Generated by Django 5.2.14 on 2026-05-08 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='parent_organization',
            field=models.ForeignKey(blank=True, help_text='Developer or agency this agent belongs to (null = independent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Dashboard login account for this agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
