# Generated by Django 5.2.14 on 2026-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', help_text='Real-time availability shown to leads and used in auto-assignment', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Uncheck to temporarily disable this agent from receiving leads'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='registration_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval state — pending until admin/developer reviews the application', max_length=20),
        ),
    ]
