# Generated by Django 5.2.14 on 2026-05-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_arch_global_first'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentorgmembership',
            new_name='agent_org_m_organiz_4bea06_idx',
            old_name='aom_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentorgmembership',
            new_name='agent_org_m_agent_i_0d1b7e_idx',
            old_name='aom_agent_status_idx',
        ),
        migrations.AlterField(
            model_name='agentorgmembership',
            name='can_access_inventory',
            field=models.BooleanField(default=True, help_text='Allow agent to view org inventory in the dashboard'),
        ),
        migrations.AlterField(
            model_name='agentorgmembership',
            name='can_receive_leads',
            field=models.BooleanField(default=True, help_text='Allow org lead routing to this agent'),
        ),
        migrations.AlterField(
            model_name='agentorgmembership',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes on the collaboration agreement'),
        ),
    ]
