# Generated by Django 5.2.14 on 2026-05-22 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_add_user_index'),
        ('organizations', '0016_data_migrate_membership_admin_to_org_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('license_number', models.CharField(blank=True, help_text='Market-issued real estate license number', max_length=50)),
                ('global_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Aggregate rating across all associated organizations', max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'freelance_agent_profiles',
            },
        ),
        migrations.CreateModel(
            name='AgentOrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('flat', 'Flat Fee'), ('percentage', 'Percentage'), ('tiered', 'Tiered')], max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelance_members', to='organizations.organization')),
                ('freelance_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to='agents.freelanceagentprofile')),
            ],
            options={
                'db_table': 'agent_organization_memberships',
                'unique_together': {('freelance_agent', 'organization')},
            },
        ),
    ]
