# Generated by Django 5.2.14 on 2026-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_freelance_agent_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National identity document number. Format varies by country: CNIC (PK), Emirates ID (AE), National Insurance (GB), SSN last-4 (US), etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='tax_id_number',
            field=models.CharField(blank=True, help_text='Tax registration number. Format varies by country: NTN (PK), TRN (AE), UTR/VAT number (GB), EIN/TIN (US), etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='cnic_number',
            field=models.CharField(blank=True, help_text='[Deprecated — use national_id_number] Pakistan CNIC (format: 12345-1234567-1)', max_length=20),
        ),
        migrations.AlterField(
            model_name='agent',
            name='ntn_number',
            field=models.CharField(blank=True, help_text='[Deprecated — use tax_id_number] Pakistan FBR National Tax Number', max_length=50),
        ),
    ]
