# Generated by Django 5.2.14 on 2026-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_add_national_id_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='companies_house_number',
            field=models.CharField(blank=True, help_text='UK Companies House registration number (GB orgs only, 8 chars)', max_length=8),
        ),
    ]
