"""US city lookup map — keyword (lowercase) → display name."""

CITY_MAP: dict[str, str] = {
    'new york':      'New York',
    'nyc':           'New York',
    'los angeles':   'Los Angeles',
    'la':            'Los Angeles',
    'chicago':       'Chicago',
    'houston':       'Houston',
    'phoenix':       'Phoenix',
    'philadelphia':  'Philadelphia',
    'philly':        'Philadelphia',
    'san antonio':   'San Antonio',
    'san diego':     'San Diego',
    'dallas':        'Dallas',
    'san jose':      'San Jose',
    'austin':        'Austin',
    'jacksonville':  'Jacksonville',
    'fort worth':    'Fort Worth',
    'columbus':      'Columbus',
    'charlotte':     'Charlotte',
    'indianapolis':  'Indianapolis',
    'san francisco': 'San Francisco',
    'sf':            'San Francisco',
    'seattle':       'Seattle',
    'denver':        'Denver',
    'miami':         'Miami',
    'atlanta':       'Atlanta',
    'boston':        'Boston',
    'las vegas':     'Las Vegas',
    'portland':      'Portland',
    'nashville':     'Nashville',
    'memphis':       'Memphis',
}
