# Generated by Django 5.0.6 on 2026-05-05 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("intent_classify", "Intent Classification"),
                            ("property_score", "Property Scoring"),
                            ("ocr", "Document OCR"),
                            ("tax_advisory", "Tax Advisory"),
                            ("loan_check", "Loan Check"),
                            ("fraud_check", "Fraud Check"),
                            ("voice_transcribe", "Voice Transcription"),
                            ("report_gen", "Report Generation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("response_tokens", models.PositiveIntegerField(default=0)),
                (
                    "model_used",
                    models.CharField(default="gemini-1.5-flash", max_length=50),
                ),
                ("was_cached", models.BooleanField(default=False)),
                ("response_ms", models.PositiveIntegerField(default=0)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_interactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
