# Generated by Django 5.2.14 on 2026-05-29 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('organizations', '0019_rename_dev_api_keys_org_active_idx_developer_a_organiz_70be96_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('model', models.CharField(default='gemini-1.5-flash', max_length=80)),
                ('intent', models.CharField(blank=True, max_length=60, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage_records', to='organizations.organization')),
            ],
            options={
                'db_table': 'ai_token_usage_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['org', 'timestamp'], name='ai_token_us_org_id_f86ecd_idx')],
            },
        ),
    ]
