# Generated by Django 5.0.6 on 2026-05-07 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=100)),
                ('area_marla', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_value_pkr', models.BigIntegerField()),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('risk_score', models.IntegerField(default=5, help_text='1–10; 1 = safest, 10 = highest risk')),
                ('investment_grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Good'), ('C', 'Fair'), ('D', 'Poor')], default='C', max_length=1)),
                ('liquidity_score', models.IntegerField(default=5, help_text='1–10; 10 = most liquid')),
                ('audit_data', models.JSONField(default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='audits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
