# Generated by Django 5.2.14 on 2026-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_arch_global_first'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditbenchmark',
            options={'ordering': ['country', 'city', 'location_key'], 'verbose_name': 'Audit Benchmark', 'verbose_name_plural': 'Audit Benchmarks'},
        ),
        migrations.RenameIndex(
            model_name='auditbenchmark',
            new_name='audit_audit_country_60f11d_idx',
            old_name='benchmark_country_city_idx',
        ),
        migrations.AlterField(
            model_name='auditbenchmark',
            name='approved',
            field=models.BooleanField(blank=True, help_text='Is the area authority-approved? Leave blank if unknown.', null=True),
        ),
        migrations.AlterField(
            model_name='auditbenchmark',
            name='city',
            field=models.CharField(help_text='e.g. lahore, islamabad, dubai, default', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditbenchmark',
            name='liq_months',
            field=models.IntegerField(help_text='Average months to sell'),
        ),
        migrations.AlterField(
            model_name='auditbenchmark',
            name='price_per_unit_max',
            field=models.BigIntegerField(help_text='Max price per size_unit in the local currency'),
        ),
        migrations.AlterField(
            model_name='auditbenchmark',
            name='price_per_unit_min',
            field=models.BigIntegerField(help_text='Min price per size_unit in the local currency'),
        ),
        migrations.AlterField(
            model_name='propertyaudit',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric area in the unit specified by area_unit', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='propertyaudit',
            name='estimated_value',
            field=models.BigIntegerField(help_text='Estimated property value in the currency specified by currency'),
        ),
    ]
