# Generated by Django 5.2.14 on 2026-05-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_securitytrace_complianceviolation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complianceviolation',
            new_name='compliance__violati_65f253_idx',
            old_name='comp_viol_type_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='complianceviolation',
            new_name='compliance__organiz_7fc90d_idx',
            old_name='comp_viol_org_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='securitytrace',
            new_name='security_tr_violati_68d4e6_idx',
            old_name='sec_trace_type_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='securitytrace',
            new_name='security_tr_phone_66dc9d_idx',
            old_name='sec_trace_phone_ts_idx',
        ),
    ]
