# Generated by Django 5.2.14 on 2026-05-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_audit_delivery_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditdeliveryfailure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propertyaudit',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
