# Generated by Django 5.2.14 on 2026-05-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationconfig'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_org_typ_b2fc82_idx',
            old_name='org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_country_99aedd_idx',
            old_name='org_country_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_is_acti_bdc355_idx',
            old_name='org_active_idx',
        ),
    ]
