# Generated by Django 5.2.14 on 2026-05-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_wa_phone_number_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('safepay', 'Safepay'), ('bsecure', 'bSecure'), ('manual', 'Manual (bank transfer / JazzCash / EasyPaisa)')], default='manual', max_length=20)),
                ('safepay_merchant_key', models.CharField(blank=True, max_length=200)),
                ('safepay_secret_key', models.CharField(blank=True, max_length=200)),
                ('safepay_environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('bsecure_client_id', models.CharField(blank=True, max_length=200)),
                ('bsecure_client_secret', models.CharField(blank=True, max_length=200)),
                ('bsecure_environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('jazzcash_number', models.CharField(blank=True, max_length=20)),
                ('easypaisa_number', models.CharField(blank=True, max_length=20)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_account_name', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='organizations.organization')),
            ],
            options={
                'db_table': 'org_payment_settings',
            },
        ),
    ]
