# Generated by Django 5.2.14 on 2026-05-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(default='PK', help_text='ISO 3166-1 alpha-2 country code, e.g. PK, AE, GB, US', max_length=2),
        ),
    ]
