# Generated by Django 5.2.14 on 2026-05-22 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('agent', 'Agent'), ('viewer', 'Viewer')], max_length=20)),
                ('employment_type', models.CharField(choices=[('internal', 'Internal'), ('freelance', 'Freelance')], default='internal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_memberships',
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_6dcab6_idx'), models.Index(fields=['user', 'is_active'], name='organizatio_user_id_c5f3a8_idx')],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
