# Generated by Django 5.2.14 on 2026-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_populate_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='measurement_system',
            field=models.CharField(choices=[('pk_traditional', 'Pakistan Traditional (Marla / Kanal)'), ('imperial', 'Imperial (Square Feet)'), ('metric', 'Metric (Square Metres)')], default='pk_traditional', help_text='Primary area unit for property listings in this org', max_length=20),
        ),
    ]
