# Generated by Django 5.2.14 on 2026-05-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_organization_measurement_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('developer', 'Real Estate Developer'), ('agency', 'Real Estate Agency'), ('brokerage', 'Brokerage Firm'), ('community_development', 'Community Development'), ('housing_society', 'Housing Society (deprecated)'), ('enterprise', 'Enterprise / Corporate')], default='agency', max_length=25),
        ),
    ]
