# Generated by Django 5.2.14 on 2026-05-22 11:14

from django.db import migrations


def rename_housing_society(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Organization.objects.filter(org_type='housing_society').update(
        org_type='community_development'
    )


def reverse_rename(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Organization.objects.filter(org_type='community_development').update(
        org_type='housing_society'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_community_development_org_type'),
    ]

    operations = [
        migrations.RunPython(rename_housing_society, reverse_rename),
    ]
