# Generated by Django 5.2.14 on 2026-05-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_data_migrate_housing_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='data_residency_region',
            field=models.CharField(choices=[('global', 'Global'), ('eu', 'European Union'), ('uk', 'United Kingdom'), ('uae', 'UAE'), ('pk', 'Pakistan')], default='global', help_text='Auto-set from country at creation. Drives GDPR module and future DB routing.', max_length=10),
        ),
    ]
