# Generated by Django 5.2.14 on 2026-05-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_data_residency_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('org_admin', 'Organization Admin'), ('team_manager', 'Team Manager'), ('sales_manager', 'Sales Manager'), ('crm_operator', 'CRM Operator'), ('agent', 'Agent'), ('freelance_agent', 'Freelance Agent'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
