# Generated by Django 5.2.14 on 2026-05-22 11:53

from django.db import migrations


def rename_admin_to_org_admin(apps, schema_editor):
    OrganizationMembership = apps.get_model('organizations', 'OrganizationMembership')
    OrganizationMembership.objects.filter(role='admin').update(role='org_admin')


def rename_org_admin_to_admin(apps, schema_editor):
    OrganizationMembership = apps.get_model('organizations', 'OrganizationMembership')
    OrganizationMembership.objects.filter(role='org_admin').update(role='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_expand_membership_roles'),
    ]

    operations = [
        migrations.RunPython(rename_admin_to_org_admin, rename_org_admin_to_admin),
    ]
