# Generated by Django 5.2.14 on 2026-05-25 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0018_developer_api_key_and_custom_domain'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='developerapikey',
            new_name='developer_a_organiz_70be96_idx',
            old_name='dev_api_keys_org_active_idx',
        ),
        migrations.AlterField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(blank=True, default='#1B4F72', help_text='Hex color code for PDF report header, e.g. #1B4F72', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, e.g. #1B4F72')]),
        ),
    ]
