# Generated by Django 5.2.14 on 2026-05-29 14:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_org_provisioning_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, e.g. #2563EB')])),
                ('secondary_color', models.CharField(default='#4F46E5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, e.g. #4F46E5')])),
                ('accent_color', models.CharField(default='#0891B2', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color, e.g. #0891B2')])),
                ('logo_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='organizations.organization')),
            ],
            options={
                'db_table': 'org_themes',
            },
        ),
    ]
