# Generated by Django 5.2.14 on 2026-05-14 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_read_notification_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('lead_updates', models.BooleanField(default=True, help_text='Lead status and assignment changes')),
                ('appointment_reminders', models.BooleanField(default=True, help_text='Upcoming visit reminders')),
                ('deal_updates', models.BooleanField(default=True, help_text='Deal lock and escrow notifications')),
                ('report_ready', models.BooleanField(default=True, help_text='Report generation completed')),
                ('marketing', models.BooleanField(default=False, help_text='Promotional and marketing messages')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_preferences',
            },
        ),
    ]
